#include <iostream>
#include <vector>

// Project Euler 
// Even Fibonacci Numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

int main(int argc, char **argv)
{
	std::vector<int> fibos;
	std::vector<int>::iterator it;
	int total = 2;
	fibos.push_back(1);
	fibos.push_back(2);
	fibos.push_back(3);
	for (int a = 5; a < 4000000; a = a+fibos[fibos.size()-2]) {
		fibos.push_back(a);
		if (a % 2 == 0) { total = total + a; }
	}
	std::cout << "total value of even elements:   " << total << std::endl;
	return 0;
}
